version: '3.8'
services:
  market-service-dev:
    image: mhmarket/rental:latest
    container_name: rental-service
    ports:
      - "9567:9567"
    environment:
      CLOUD_CONFIG_URL: http://103.162.20.141:8888
      CLOUD_CONFIG_PROFILE: dev
      CLOUD_CONFIG_LABEL: master
    restart: unless-stopped
    networks:
      - mh-network
    dns:
      - 192.168.200.4
      - 8.8.8.8
networks:
  mh-network:
    driver: bridge